name: GitHub Actions without Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JWT_TOKEN_TIME: 120
      PSQL_DBNAME: jesus_uribedb
      PSQL_USERNAME: jesus_uribe
      PSQL_PASS: 1701
      PSQL_HOST: localhost
      PSQL_PORT: 5432
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: jesus_uribe
          POSTGRES_PASSWORD: 1701
          POSTGRES_DB: jesus_uribedb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run migrations
        run: python manage.py migrate
      - name: Run tests
        run: python manage.py test
